package ua.gladiator.taxi.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import ua.gladiator.taxi.model.entities.Client;
import ua.gladiator.taxi.model.entities.SocialStatus;
import ua.gladiator.taxi.model.repository.ClientRepository;

import java.math.BigDecimal;

@Controller
@RequestMapping(path = "/")
public class TaxiController {

    @RequestMapping(value = { "/", "/index" }, method = RequestMethod.GET)
    public String index(Model model) {



        return "index";
    }


     // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private ClientRepository clientRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser (@RequestParam String login,
                       @RequestParam String password,
                       @RequestParam String socialStatus,
                       @RequestParam BigDecimal totalSpentValue,
                       @RequestParam String userType,
                       @RequestParam Integer personalDiscount
                       ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Client n = new Client();
        n.setLogin(login);
        n.setPassword(password);
        n.setPersonalDiscount(personalDiscount);
        n.setSocialStatus(SocialStatus.valueOf(socialStatus));
        n.setTotalSpentValue(totalSpentValue);
        n.setUserType(userType);
        clientRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Client> getAllClients() {
        // This returns a JSON or XML with the users
        return clientRepository.findAll();
    }
}